name: Security
on:
  schedule: [ { cron: "0 9 * * *" } ]
  pull_request:
permissions:
  contents: read
  security-events: write
jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          publish_results: false
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
