name: Branch protection compliance
on:
  pull_request:

permissions:
  contents: read
  checks: read

jobs:
  check:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.base.ref == github.event.repository.default_branch
      && !github.event.pull_request.head.repo.fork
    steps:
      - name: Verify Cogni check exists and passed
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          CHECK_NAME: Cogni Git PR Review
          # Use PR head SHA if available, otherwise use the current commit
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -euo pipefail

          echo "Verifying '$CHECK_NAME' check exists and passed for commit $HEAD_SHA"
          
          # Retry loop to avoid races with the bot (9 attempts x 5s = 45s max wait)
          for attempt in {1..9}; do
            echo "Attempt $attempt: Checking for '$CHECK_NAME'..."
            
            # Query check runs and get the most recent matching check
            if check_run=$(gh api -H "Accept: application/vnd.github+json" \
                  "repos/$OWNER/$REPO/commits/$HEAD_SHA/check-runs" \
                  --jq '.check_runs[] | select(.name == "'"$CHECK_NAME"'") | sort_by(.started_at) | last' 2>/tmp/gh_err); then
              
              if [[ -n "$check_run" && "$check_run" != "null" ]]; then
                # Found the check, verify it passed
                conclusion=$(echo "$check_run" | jq -r '.conclusion')
                status=$(echo "$check_run" | jq -r '.status')
                
                if [[ "$status" != "completed" ]]; then
                  echo "⏳ Check '$CHECK_NAME' not yet completed (status: $status)"
                elif [[ "$conclusion" != "success" ]]; then
                  echo "❌ Check '$CHECK_NAME' failed (conclusion: $conclusion)"
                  echo "$check_run" | jq -r '"Details: " + .html_url'
                  exit 1
                else
                  echo "✅ Check '$CHECK_NAME' exists and passed for commit $HEAD_SHA"
                  echo "ℹ️ Check details:"
                  echo "$check_run" | jq -r '"Status: " + .status + ", Conclusion: " + .conclusion + ", URL: " + .html_url'
                  exit 0
                fi
              else
                echo "⏳ Check '$CHECK_NAME' not found yet..."
              fi
            else
              echo "⚠️ Failed to fetch check runs:"
              cat /tmp/gh_err
            fi
            
            if [[ $attempt -lt 9 ]]; then
              echo "Waiting 5s before retry..."
              sleep 5
            fi
          done

          echo "❌ Required check '$CHECK_NAME' not found after 45s timeout"
          echo "Available checks:"
          gh api "repos/$OWNER/$REPO/commits/$HEAD_SHA/check-runs" --jq '.check_runs[].name' || echo "None"
          exit 1
