name: E2E Test (Preview)
permissions:
  contents: read
  actions: read
on:
  workflow_run:
    workflows: ["Deploy (Preview)"]
    types: [completed]
  workflow_dispatch:
concurrency:
  group: e2e-preview-${{ github.event.workflow_run.head_branch || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: preview-E2E-testing
    env:
      NODE_ENV: test # E2E test runner environment (separate from preview deployment being validated)
      TEST_REPO_GITHUB_PAT: ${{ secrets.TEST_REPO_GITHUB_PAT }}
      TEST_REPO: ${{ vars.TEST_REPO }}
      APP_ENV: preview # required for e2e-runner.js computing PR_REVIEW_NAME via src/constants.js
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - name: Configure git creds from PAT
        run: |
          unset GH_TOKEN                                  
          printf '%s' "$TEST_REPO_GITHUB_PAT" | gh auth login --with-token --hostname github.com
          gh auth setup-git
          git config --global user.name  "cogni-bot"
          git config --global user.email "actions@users.noreply.github.com"
      - run: npm run e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-artifacts
          path: e2e/artifacts/
          if-no-files-found: warn
          retention-days: 7
