name: Secrets Scan (Gitleaks)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Install gitleaks
        run: |
          curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash
      - name: Run gitleaks (SARIF)
        run: |
          ./gitleaks detect --source . \
            --report-format sarif \
            --report-path gitleaks.sarif || true
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if gitleaks finds issues
        with:
          name: gitleaks.sarif
          path: gitleaks.sarif
          retention-days: 7